### ISSUE TITLE
Missing Train 391

### ISSUE THREAD

**Issue by trek-boldly-go** [piemadd/amtraker-next#1]
Train 391 runs from Chicago, IL to Carbondale, IL and I can see it on the [official Amtrak "track your train"](https://www.amtrak.com/track-your-train.html) website, but I can't see it on the Amtraker.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/66212896/219140204-9492c8e8-789c-496e-8200-687422f29a37.png">

<img width="640" alt="image" src="https://user-images.githubusercontent.com/66212896/219140552-1c3ac3e5-8a1b-4b77-af32-512f2a9f1b1c.png">

**Comment by trek-boldly-go** [comment]
Seeing as this was a full year ago and can't be reproduced, I'll take the liberty to close this issue.

**Comment by piemadd** [comment]
Whoops, never caught this. The infrastructure behind amtraker (since this) has been fully redone, so (fingers crossed) it doesnt happen again lol.
